# Generated by Django 3.0.7 on 2020-06-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200615_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogEntry')),
            ],
        ),
    ]
