# Generated by Django 3.0.7 on 2020-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
