# Generated by Django 3.0.7 on 2020-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_picture_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='entry',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='pictures',
            field=models.ManyToManyField(to='blog.Picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
    ]
